version: '3.4'

services:
  database:
    image: mysql:latest
    volumes:
        - dbdata:/var/lib/mysql
    restart: always
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: oauthDB
        MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

volumes:
  dbdata: